Jwt authorisation piotrkowe
petercieslak/flower-shop-se2 pull request #31
Opened 2023-04-04 19:52 UTC by ananasek727

2023-04-04 20:05 UTC, petercieslak requested changes

2023-04-04 20:05 UTC, petercieslak commented on flower-shop/docker-compose.yml
> +      - MYSQL_DATABASE=SAstudent1
czemu to zmienione?

2023-04-04 20:05 UTC, petercieslak commented on flower-shop/src/main/java/com/flower/shop/data/models/Employee.java
> +public class Employee extends Person implements UserDetails {
do wywalenia

2023-04-04 20:05 UTC, petercieslak commented on flower-shop/src/main/java/com/flower/shop/rest/AuthenticationService.java
to nie powinno byc w package rest, mozesz zrobic package authentication w application

2023-04-04 20:05 UTC, petercieslak commented on flower-shop/src/main/java/com/flower/shop/rest/AuthenticationRequest.java
to nie powinno byc w package rest, mozesz zrobic package authentication w application

2023-04-04 20:05 UTC, petercieslak commented on flower-shop/src/main/java/com/flower/shop/rest/RegisterRequest.java
to nie powinno byc w package rest, mozesz zrobic package authentication w application

2023-04-04 20:05 UTC, petercieslak commented on flower-shop/src/main/java/com/flower/shop/config/JwtService.java
to nie powinno byc w config

2023-04-04 20:16 UTC, simonsrz commented on flower-shop/src/main/java/com/flower/shop/rest/AuthenticationRequest.java
czemu tutaj haslo nie jest private?

2023-04-04 20:16 UTC, ananasek727 commented on flower-shop/src/main/java/com/flower/shop/data/models/Employee.java
> +public class Employee extends Person implements UserDetails {
co ty gadasz, pojebało cię, tak powinno być

2023-04-04 20:17 UTC, ananasek727 commented on flower-shop/docker-compose.yml
> +      - MYSQL_DATABASE=SAstudent1
przeoczenie

2023-04-04 20:18 UTC, ananasek727 commented on flower-shop/src/main/java/com/flower/shop/config/JwtService.java
a gdzie?

2023-04-04 20:25 UTC, petercieslak requested changes

2023-04-04 20:25 UTC, petercieslak commented on flower-shop/src/main/java/com/flower/shop/data/models/Employee.java
> +public class Employee extends Person implements UserDetails {
to dlaczego zrobiles to tu a w cliencie juz nie? Niczym sie te tabele wzgledem siebie nie roznia

2023-04-04 20:25 UTC, petercieslak commented on flower-shop/src/main/java/com/flower/shop/config/JwtService.java
to jest serwis, zobacz gdzie sa serwisy w projekcie

2023-04-04 20:26 UTC, petercieslak commented on flower-shop/src/main/java/com/flower/shop/config/JwtService.java
https://www.techtarget.com/searchsoftwarequality/definition/3-tier-application

2023-04-04 20:35 UTC, petercieslak commented on flower-shop/src/main/java/com/flower/shop/Main.java
> +    public BCryptPasswordEncoder bCryptPasswordEncoder() {
czemu to jest tutaj?

2023-04-06 08:08 UTC, simonsrz approved these changes

2023-04-07 08:24 UTC, petercieslak approved these changes

2023-04-07 08:25 UTC, merged